# Site settings
title: Fully Forged
email: info@fullyforged.com
description: > # this means to ignore newlines until "baseurl:"
  Fully Forged specializes in bespoke web applications and training for Elixir, JavaScript and Ruby.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.fullyforged.com" # the base hostname & protocol for your site
twitter_username: fully_forged
github_username:  fully-forged
show_posts: true
availability:
  build: June 2016
  train: February 2016

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title.html
excerpt_separator: <!--more-->

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Assets
assets:
  prefix: "/assets"
  assets:
    - "*.png"
    - "main.scss"
  digest: true
  sources:
    - "_images"
    - "css"
    - "_sass"
